markdown:         rdiscount
pygments:         true
permalink:        /:categories/:title

title:            WebCraft
url:              http://malei0311.github.io
feed:             /atom.xml

author:
  name:         Lei Ma
  email:        leiman0311@gmail.com
  twitter:      twitter.com/malei0311

description:      "malei0311\'s Blog"
author_info:      <a href="http://malei0311.github.io/about">malei0311</a>
keywords:         malei0311
copyright:
    - Design by <a href="http://malei0311.github.io/about.html" title="malei0311" target="_blank">malei0311</a> &copy; Copyright 2013
